kind: ConfigMap
apiVersion: v1
metadata:
  name: local-path-config
  namespace: default
data:
  config.json: |-
        {
                "nodePathMap":[
                {
                        "node":"DEFAULT_PATH_FOR_NON_LISTED_NODES",
                        "paths":["/opt"]
                },
                {
                        "node":"yasker-lp-dev1",
                        "paths":["/opt", "/data1"]
                },
                {
                        "node":"yasker-lp-dev3",
                        "paths":["/data3"]
                }
                ]
        }

